title: "NestJS 公式ドキュメントver7日本語訳"
summary: " フルスタックサーバーサイドフレームワークNestのドキュメントを日本語訳します。DeepL翻訳を下敷きとし、ある程度一人でやる意志ではありますが（目標：～securityパート）、githubからの自動デプロイですので、ぜひプルリクエストを下さい。　https://github.com/kisihara-c/nest-officialdoc-jp "
topics: ["Nest","NestJS","Node.js","Web"]
published: true
price: 0
chapters: 
  - introduction
  - overview-firststeps
  - overview-controllers
  - overview-providers
  - overview-modules
  - overview-middleware
  - overview-excepitonfilters
  - overview-pipes
  - overview-guards
toc_depth: 2