title: "Nest 公式ドキュメントver7日本語訳"
summary: フルスタックサーバーサイドフレームワークNestを日本語訳します。
DeepL翻訳を下敷きとし、ある程度一人でやる意志ではありますが（目標：～securityパート）、
githubからの自動デプロイですので、ぜひプルリクエストを下さい。
https://github.com/kisihara-c/nest-officialdoc-jp "
tag: ["Nest","NestJS","Node.js","Web"]
price: 0
chapters: 
  - OVERVIEW-FirstSteps
toc_depth: 2